apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-image-pr
  namespace: demo
spec:         
  serviceAccountName: tekton-triggers-example-sa
  pipelineRef:
    name: "boa-pipeline"
  timeout: 1h0m0s
  workspaces:
  - name: git-source
    persistentVolumeClaim:
      claimName: mypvc
