apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: boa-pipeline
  namespace: demo  
spec:
  params:
    - name: image-registry
      default: docker.io/gauravkr19
  workspaces:
    - name: git-source
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/gauravkr19/boa-workflow.git
        - name: revision
          value: master
      workspaces:
        - name: output
          workspace: git-source
    - name: build-image-balreader
      taskRef:
        name: jib-maven
      runAfter: [fetch-from-git]
      params:
        - name: IMAGE
          value: $(params.image-registry)/balreader
        - name: DIRECTORY
          value: ./src/balancereader/
      workspaces:
        - name: source
          workspace: git-source                                                            
    - name: build-image-ledgerwriter
      taskRef:
        name: jib-maven
      runAfter: [fetch-from-git]        
      params:
        - name: IMAGE
          value: $(params.image-registry)/ledgerwriter
        - name: DIRECTORY
          value: ./src/ledgerwriter/
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image-transhistory
      taskRef:
        name: jib-maven
      runAfter: [fetch-from-git]        
      params:
        - name: IMAGE
          value: $(params.image-registry)/transactionhistory
        - name: DIRECTORY
          value: ./src/transactionhistory
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image-userservice    
      taskRef:
        name: kaniko
      runAfter: [fetch-from-git]        
      params:
        - name: IMAGE
          value: $(params.image-registry)/userservice
        - name: CONTEXT
          value: ./src/userservice
        - name: DOCKERFILE
          value: ./src/userservice/Dockerfile
      workspaces:
        - name: source
          workspace: git-source   
    - name: build-image-contacts
      taskRef:
        name: kaniko
      runAfter: [fetch-from-git]        
      params:
        - name: IMAGE
          value: $(params.image-registry)/contacts
        - name: CONTEXT
          value: ./src/contacts
        - name: DOCKERFILE
          value: ./src/contacts/Dockerfile
      workspaces:
        - name: source
          workspace: git-source 
    - name: build-image-frontend
      taskRef:
        name: kaniko
      runAfter: [fetch-from-git]        
      params:
        - name: IMAGE
          value: $(params.image-registry)/frontend
        - name: CONTEXT
          value: ./src/frontend
        - name: DOCKERFILE
          value: ./src/frontend/Dockerfile
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image-loadgenerator
      taskRef:
        name: kaniko
      runAfter: [fetch-from-git]        
      params:
        - name: IMAGE
          value: $(params.image-registry)/loadgenerator
        - name: CONTEXT
          value: ./src/loadgenerator
        - name: DOCKERFILE
          value: ./src/loadgenerator/Dockerfile
      workspaces:
        - name: source
          workspace: git-source    
    - name: build-image-accounts-db
      taskRef:
        name: kaniko
      runAfter: [fetch-from-git]        
      params:
        - name: IMAGE
          value: $(params.image-registry)/accounts-db
        - name: CONTEXT
          value: ./src/accounts-db
        - name: DOCKERFILE
          value: ./src/accounts-db/Dockerfile
      workspaces:
        - name: source
          workspace: git-source 
    - name: build-image-ledger-db
      taskRef:
        name: kaniko
      runAfter: [fetch-from-git]        
      params:
        - name: IMAGE
          value: gcr.io/playground-s-11-ffad36f2/ledger-db
        - name: CONTEXT
          value: ./src/ledger-db
        - name: DOCKERFILE
          value: ./src/ledger-db/Dockerfile
      workspaces:
        - name: source
          workspace: git-source                                                    
    - name: image-change-ledgerdb
      taskRef:
        name: app-deploy-kubectl
      runAfter: [build-image-ledger-db]
      params:
      - name: imageURL
        value: gcr.io/playground-s-11-ffad36f2/ledger-db@$(tasks.build-image-ledger-db.results.IMAGE-DIGEST)
      - name: path
        value: $(workspaces.source.path)/extras/asm-multicluster/kubernetes-manifests-db/ledger-db.yaml
      - name: yqArg
        value: "-d0"
      - name: yamlPathToImage
        value: "spec.template.spec.containers[0].image"
      workspaces:
      - name: source
        workspace: git-source    
    - name: gke-deploy-ledgerdb
      taskRef:
        name: gke-deploy
      runAfter: [image-change-ledgerdb]      
      params:
        - name: ARGS
          value:
            - 'run'
            - '--filename=$(workspaces.source.path)/extras/asm-multicluster/kubernetes-manifests-db'
            - '--cluster=tektoncl'
            - '--location=us-central1-a'
            - '--project=playground-s-11-ffad36f2'
            - '--output=/var/tmp/gke-deploy'
      workspaces:
        - name: source
          workspace: git-source              